# -*- coding: utf-8 -*-
"""CGA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RdVOI0JUoyUD76hmztkGywgRnC3V7m_v
"""

from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain_openai import ChatOpenAI  # point to your vLLM/SGLang endpoint
import subprocess, json, textwrap, os

SYSTEM = """You are a competitive programming and software engineering assistant..."""

def build_messages(problem, tests, context_files=None):
    msgs = [SystemMessage(content=SYSTEM)]
    ctx_block = ""
    if context_files:
        for path, content in context_files.items():
            ctx_block += f"=== FILE: {path} ===\n{content}\n\n"
    user_text = f"Problem:\n{problem}\n\nConstraints:\n{constraints}\n\nTest cases:\n{tests}\n\n"
    if ctx_block:
        user_text += f"Context files:\n{ctx_block}"
    msgs.append(HumanMessage(content=user_text))
    return msgs

def run_in_sandbox(code: str, tests: list[dict], timeout: int = 5):
    # Write code to a temp file; run each test in isolated Docker or firecracker microVM.
    # Here’s a minimal subprocess sketch (replace with proper sandbox).
    with open("/tmp/solution.py", "w") as f:
        f.write(code)
    results = []
    for t in tests:
        inp = t["input"]
        expected = t["output"]
        try:
            proc = subprocess.run(
                ["python3", "/tmp/solution.py"],
                input=inp, text=True, capture_output=True, timeout=timeout
            )
            out = proc.stdout
            err = proc.stderr
            passed = (out.strip() == expected.strip()) and (proc.returncode == 0)
            results.append({"passed": passed, "stdout": out, "stderr": err, "returncode": proc.returncode})
        except subprocess.TimeoutExpired:
            results.append({"passed": False, "stderr": "Timeout", "stdout": "", "returncode": -1})
    return results

def agent_loop(problem, tests, context_files=None, max_iters=4):
    model = ChatOpenAI(
        base_url="http://localhost:8000/v1",  # vLLM/SGLang
        model="tencent/Hy4-preview",
        temperature=0.2,
        max_tokens=4096,
    )
    messages = build_messages(problem, tests, context_files)
    for i in range(max_iters):
        response = model.invoke(messages)
        code = extract_code_block(response.content)  # implement parser
        results = run_in_sandbox(code, tests)
        if all(r["passed"] for r in results):
            return {"success": True, "code": code, "iters": i+1, "results": results}
        # prepare debug feedback
        failing = next(r for r in results if not r["passed"])
        debug_msg = (
            f"Execution failed.\nStderr:\n{failing['stderr']}\n"
            f"Failing input:\n{tests[results.index(failing)]['input']}\n"
            f"Current code:\n{code}\n\n"
            "Task: Diagnose the bug in 2–4 sentences, then output only the corrected code block."
        )
        messages += [AIMessage(content=response.content), HumanMessage(content=debug_msg)]
    return {"success": False, "code": code, "iters": max_iters, "results": results}
